swiftmailer:
    transport:        smtp
    username:          '%env(MAILER_ADDRESS)%'
    password:         '%env(MAILER_PASSWORD)%'
    host:             192.168.10.5
    port:             25
    auth-mode:        login
    spool: { type: 'memory' }

