swiftmailer:
    transport:        gmail
    username:         logan2.humbert@gmail.com
    password:         '%env(MAILER_PASSWORD)%'
    host:             smtp.gmail.com
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
